	CREATECHUNK('SCEN', SCENChunk)

	CREATECHUNK('CAME', CAMEChunk)
	CREATECHUNK('FCAM', FCAMChunk)
	CREATECHUNK('TCAM', TCAMChunk)

	CREATECHUNK('MESH', MESHChunk)

	CREATECHUNK('LITE', LITEChunk)
	CREATECHUNK('SLIT', SLITChunk)
	CREATECHUNK('PLIT', PLITChunk)
	CREATECHUNK('DLIT', DLITChunk)

#ifndef _WIN64	// "temporary"
	CREATECHUNK('MATL', MATLChunk)
#endif
	CREATECHUNK('TXMP', TXMPChunk)

	CREATECHUNK('BGIZ', BGIZChunk)
	CREATECHUNK('SGIZ', SGIZChunk)
	CREATECHUNK('CGIZ', CGIZChunk)
	CREATECHUNK('HELP', HELPChunk)
	CREATECHUNK('SKEL', SKELChunk)

	CREATECHUNK('SHAP', SHAPChunk)

	CREATECHUNK('SAMP', SAMPChunk)
	CREATECHUNK('ROTA', ROTAChunk)
	CREATECHUNK('MOVE', MOVEChunk)

